### ISSUE TITLE
Terrains rendering fails when using a GPU not supporting GLSL 1.40

### ISSUE THREAD

**Issue by vloup** [kcat/opendf#6]
In commit 9d2e4a0, you made both terrain.vert and terrain.frag use GLSL version 1.40.
Sadly my Intel HD4000 supports GLSL up to 1.30 (confirmed by glxinfo;  core profile GLSL goes up to version 3.30) and thus could not render the ground. Using the discrete nvidia card (with the closed-source driver) instead is fine but uses way more battery.

**Comment by kcat** [comment]
Odd that the device only supports GL3.0 with a compatibility profile, while a core profile is needed for GL3.3 (GLSL 1.40 is equivalent to GL3.1). IIRC, the later GL3.x versions were designed specifically so that they would work without requiring a core profile.

Does it work if you replace `#version 140` with

```
#version 130
#extension GL_ARB_draw_instanced : enable
```

?

**Comment by vloup** [comment]
Yes it does work. Nice!

My glxinfo output if you want to see it: https://gist.github.com/vloup/a5d8f74814a3fb12a9d2

**Comment by kcat** [comment]
Should be fixed now in commit 17d2b1295605a0adf2b942a22dd5b19933182557. Thanks for the feedback!
